window.MEMESI_DATA = {
  currentRound: 42,
  countdownSeconds: 277,
  platform: { memes: 30, words: 307, online: 17 },
  contract: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  submissions: [
    { word: "UNEMPLOYMENT", score: 482, user: "trenchlord" },
    { word: "PENGUIN", score: 391, user: "anon_420" },
    { word: "TRENCHES", score: 344, user: "trenchlord" },
    { word: "DIVORCE", score: 287, user: "walletwife" },
    { word: "KEBAB", score: 221, user: "kebabdealer" },
    { word: "SOLANA", score: 198, user: "anon_420" },
    { word: "RENT", score: 143, user: "unemployed" },
    { word: "MOM", score: 91, user: "basementdweller" },
    { word: "NIGHTSHIFT", score: 66, user: "froglabor" },
    { word: "TAXES", score: 43, user: "zeroiq" },
    { word: "DOG", score: 28, user: "hotwallet" }
  ],
  users: [
    {name:"trenchlord",wins:7,words:31,memes:9,boosts:614,winning:["TRENCHES","UNEMPLOYMENT","DEBT"]},
    {name:"anon_420",wins:5,words:24,memes:7,boosts:488,winning:["PENGUIN","SOLANA","CASINO"]},
    {name:"kebabdealer",wins:5,words:22,memes:6,boosts:420,winning:["KEBAB","GARLIC","LIQUIDATION"]},
    {name:"unemployed",wins:4,words:19,memes:5,boosts:311,winning:["RENT","NIGHTSHIFT","CV"]},
    {name:"walletwife",wins:3,words:17,memes:4,boosts:276,winning:["WIFE","DIVORCE","WALLET"]},
    {name:"froglabor",wins:3,words:14,memes:4,boosts:233,winning:["FROG","PUMP","NIGHTSHIFT"]},
    {name:"basementdweller",wins:2,words:13,memes:3,boosts:182,winning:["MOM","BASEMENT"]},
    {name:"zeroiq",wins:2,words:12,memes:3,boosts:161,winning:["TAXES","BRAIN"]},
    {name:"hotwallet",wins:2,words:11,memes:2,boosts:140,winning:["DOG","WALLET"]},
    {name:"chartgoblin",wins:2,words:10,memes:2,boosts:128,winning:["CANDLE","CHART"]},
    {name:"exitliquidity",wins:1,words:9,memes:2,boosts:119,winning:["LAMBO"]},
    {name:"momscard",wins:1,words:8,memes:1,boosts:91,winning:["GROCERIES"]},
    {name:"wifi_thief",wins:1,words:7,memes:1,boosts:84,winning:["WIFI"]},
    {name:"paperhands",wins:1,words:7,memes:1,boosts:73,winning:["SELL"]},
    {name:"nightmod",wins:1,words:6,memes:1,boosts:69,winning:["MOD"]},
    {name:"gasfee",wins:1,words:6,memes:1,boosts:61,winning:["FEE"]},
    {name:"bagholderjr",wins:1,words:5,memes:1,boosts:54,winning:["BAG"]},
    {name:"no_sleep",wins:1,words:5,memes:1,boosts:47,winning:["COFFEE"]},
    {name:"pixelpeasant",wins:0,words:5,memes:0,boosts:42,winning:[]},
    {name:"routerdad",wins:0,words:4,memes:0,boosts:38,winning:[]},
    {name:"capitulation",wins:0,words:4,memes:0,boosts:31,winning:[]},
    {name:"chairmanmeow",wins:0,words:3,memes:0,boosts:29,winning:[]},
    {name:"dialupking",wins:0,words:3,memes:0,boosts:22,winning:[]},
    {name:"ctrl_alt_debt",wins:0,words:2,memes:0,boosts:18,winning:[]}
  ],
  rounds: [
    {round:41,words:["PENGUIN","UNEMPLOYMENT","TRENCHES"],scores:[482,391,344],contributors:["anon_420","trenchlord","trenchlord"],scene:"office",caption:"bro applied to the trenches",output:"A pixel penguin at an unemployment office trading memecoins on a laptop."},
    {round:40,words:["RENT","SOLANA","MOM"],scores:[413,366,298],contributors:["unemployed","anon_420","basementdweller"],scene:"bedroom",caption:"rent can wait",output:"A nervous pixel trader hides a hardware wallet while mom stands at the door."},
    {round:39,words:["KEBAB","LIQUIDATION","DOG"],scores:[399,321,277],contributors:["kebabdealer","kebabdealer","hotwallet"],scene:"kebab",caption:"bro has two sources of income",output:"A dog runs a kebab shop while a red liquidation warning fills the window."},
    {round:38,words:["CASINO","WIFE","WALLET"],scores:[441,309,254],contributors:["anon_420","walletwife","hotwallet"],scene:"casino",caption:"she thinks we're here for dinner",output:"A gambler hides a crypto wallet from his wife at a casino table."},
    {round:37,words:["FROG","NIGHTSHIFT","PUMP"],scores:[372,330,288],contributors:["froglabor","unemployed","froglabor"],scene:"nightshop",caption:"one more launch then sleep",output:"A tired frog works a night shift while watching a green candle on a CRT."},
    {round:36,words:["CAT","MONITORS","FEES"],scores:[349,303,240],contributors:["chairmanmeow","chartgoblin","gasfee"],scene:"monitors",caption:"one tab is doing numbers",output:"A pixel cat stares at fourteen monitors, thirteen of which show errors."},
    {round:35,words:["KNIGHT","DEBT","DUNGEON"],scores:[410,355,229],contributors:["trenchlord","trenchlord","pixelpeasant"],scene:"dungeon",caption:"quest reward: more debt",output:"An unemployed knight enters a crypto dungeon carrying overdue bills."},
    {round:34,words:["CANDLE","HOUSE","LEVERAGE"],scores:[386,312,267],contributors:["chartgoblin","routerdad","exitliquidity"],scene:"candle",caption:"green means structurally sound",output:"A giant green candle erupts through the roof of a tiny suburban house."},
    {round:33,words:["BUSINESSMAN","BRIEFCASE","MEME"],scores:[365,300,245],contributors:["zeroiq","bagholderjr","anon_420"],scene:"briefcase",caption:"the fundamentals are inside",output:"A businessman opens a briefcase containing exactly one low-resolution meme."},
    {round:32,words:["BASEMENT","MOM","LAMBO"],scores:[342,318,270],contributors:["basementdweller","basementdweller","exitliquidity"],scene:"garage",caption:"pre-revenue transportation",output:"A cardboard supercar is unveiled in mom's basement."},
    {round:31,words:["TAXES","DOG","PRINTER"],scores:[438,291,213],contributors:["zeroiq","hotwallet","dialupking"],scene:"printer",caption:"he knows what you did",output:"A dog accountant watches a printer endlessly produce tax forms."},
    {round:30,words:["WIFI","PIZZA","SEEDPHRASE"],scores:[327,282,201],contributors:["wifi_thief","no_sleep","hotwallet"],scene:"pizza",caption:"free wifi was not free",output:"A pizza delivery box steals a seed phrase through public Wi-Fi."},
    {round:29,words:["COFFEE","CHART","3AM"],scores:[404,296,186],contributors:["no_sleep","chartgoblin","nightmod"],scene:"coffee",caption:"technical analysis is a beverage",output:"A mug studies a chart at 3 AM while the trader sleeps upright."},
    {round:28,words:["SELL","PANIC","BUTTON"],scores:[352,279,205],contributors:["paperhands","capitulation","dialupking"],scene:"button",caption:"diamond hands loading...",output:"A terrified finger hovers above a huge red sell button."},
    {round:27,words:["GROCERIES","BAG","MOON"],scores:[319,255,198],contributors:["momscard","bagholderjr","anon_420"],scene:"grocery",caption:"forgot the milk. bought the dip.",output:"A shopping cart launches toward the moon carrying one suspicious bag."},
    {round:26,words:["MOD","BANHAMMER","RUG"],scores:[390,266,177],contributors:["nightmod","zeroiq","capitulation"],scene:"mod",caption:"source: trust me bro",output:"A sleepy forum moderator guards a rug with a foam ban hammer."},
    {round:25,words:["FEE","BRIDGE","GOAT"],scores:[306,244,190],contributors:["gasfee","routerdad","kebabdealer"],scene:"bridge",caption:"the goat paid both ways",output:"A goat pays a transaction fee to cross a bridge that goes nowhere."},
    {round:24,words:["CV","CEO","BASEMENT"],scores:[337,251,169],contributors:["unemployed","zeroiq","basementdweller"],scene:"interview",caption:"founder mode since tuesday",output:"A basement founder interviews himself for the CEO job."},
    {round:23,words:["GARLIC","VAMPIRE","CHART"],scores:[298,230,151],contributors:["kebabdealer","paperhands","chartgoblin"],scene:"vampire",caption:"cannot enter without liquidity",output:"A vampire is repelled by a garlic-shaped price chart."},
    {round:22,words:["BRAIN","MICROWAVE","ALPHA"],scores:[275,214,133],contributors:["zeroiq","momscard","trenchlord"],scene:"microwave",caption:"alpha ready in 30 seconds",output:"A tiny brain rotates inside a microwave broadcasting trading signals."}
  ],
  activities: [
    "anon_420 boosted PENGUIN +42","trenchlord submitted RENT","UNEMPLOYMENT moved to #1",
    "kebabdealer boosted KEBAB +69","{online} users watching","new submission: DIVORCE",
    "PENGUIN entered the top 3","MEMER-01 is confused","machine temperature: concerning",
    "walletwife boosted DIVORCE +24","froglabor submitted NIGHTSHIFT","internet damage remains local"
  ]
};
